### ISSUE TITLE
the invalid syntax

### ISSUE THREAD

**Issue by pig20312** [JetsonHacksNano/CSI-Camera#12]
Sorry, @jetsonhacks, 
i am a beginner in this field, when i ran this program, it said that syntax error.
and how should i change for this.

THX
Larry

https://github.com/JetsonHacksNano/CSI-Camera/blob/3be3d52e460016de9f092f4a008cbe35cc289962/simple_camera.py#L27

**Comment by satyajithj** [comment]
Are you using Python3?
If yes, replace that with `print(gstreamer_pipeline(flip_method=0))`

Take note to replace other print statements with similar syntax.
`print xyz` with `print(xyz)`

**Comment by JetsonHacksNano** [comment]
The repository has been updated to support Python 3 syntax.
