### ISSUE TITLE
Unable to access camera mode 1280x720 (60 FPS)

### ISSUE THREAD

**Issue by satyajithj** [JetsonHacksNano/CSI-Camera#13]
In available modes there is `GST_ARGUS: 1280 x 720 FR = 59,999999`.

However, when I try to access this mode using `FR = 60/1` it defaults to
`GST_ARGUS: 1280 x 720 FR = 120,000005`.

Any help regarding this?

**Comment by JetsonHacksNano** [comment]
You didn't mention how you requested the mode.
