### ISSUE TITLE
Unable to open camera use python3

### ISSUE THREAD

**Issue by haolingyi** [JetsonHacksNano/CSI-Camera#16]
Use opencv version is 3.2.0

**Comment by haolingyi** [comment]
Use opencv-3.2.0

**Comment by haolingyi** [comment]
I can use it by opencv version  3.4.6
you can install it  by the methon in this blog:
https://blog.csdn.net/hhaowang/article/details/102707777

**Comment by JetsonHacksNano** [comment]
This repository requires OpenCV version 3.3.1 which is the standard Jetson Nano install on L4T 32.2.1.
