### ISSUE TITLE
CSI camera with YoloV3-tiny

### ISSUE THREAD

**Issue by aguilaair** [JetsonHacksNano/CSI-Camera#17]
Hello,

Quick question. What would the code be to run Yolov3 tiny with the Jetson Nano connected to the CSI camera?

Thanks in advance!

**Comment by JetsonHacksNano** [comment]
https://devtalk.nvidia.com/default/topic/1061013/deepstream-sdk/how-to-use-csi-camera-in-deepstream-yolov3-tiny-/
