### ISSUE TITLE
How to capture CSI camera from /dev/video1?

### ISSUE THREAD

**Issue by RyanC1681** [JetsonHacksNano/CSI-Camera#23]
Hi,
  I can get camera pre-view window for /dev/video0 by the command as below:
gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM),width=3820, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw,width=960, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e

How to capture CSI camera from /dev/video1?
Thanks

**Comment by JetsonHacksNano** [comment]
# sensor_id selects the camera: 0 or 1 on Jetson Nano B01
$ gst-launch-1.0 nvarguscamerasrc sensor_id=0 ! nvoverlaysink
