### ISSUE TITLE
print statement error

### ISSUE THREAD

**Issue by ozett** [JetsonHacksNano/CSI-Camera#4]
https://github.com/JetsonHacksNano/CSI-Camera/blob/master/simple_camera.py#L43
shoudl be with parantheses:

print ('Unable to open camera')

**Comment by ozett** [comment]
and anoter type-error for python, i guess:

https://github.com/JetsonHacksNano/CSI-Camera/blob/master/simple_camera.py#L27

**Comment by JetsonHacksNano** [comment]
The repository has been updated for Python 3. Thank you for finding the issue.
