### ISSUE TITLE
How to send the video of the raspberry pi camera module with Jetson Nano to any server.

### ISSUE THREAD

**Issue by ashishbharadwaj100** [JetsonHacksNano/CSI-Camera#5]
How to send the video of the raspberry pi camera module with Jetson Nano to any server. Does anyone have done this??

**Comment by nijisakai** [comment]
try *mgpg-streamer* as used on RPI

**Comment by ashishbharadwaj100** [comment]
Yes I tried nijisakai 
they have given this link also 
https://devtalk.nvidia.com/default/topic/1055213/jetson-nano/mjpg-streamer-/

Then I disable the opencv with this configuration and given this command.

cd mjpg-streamer-experimental

From this link I got the idea of disable the open cv
https://devtalk.nvidia.com/default/topic/1055213/jetson-nano/mjpg-streamer-/

cmake -DPLUGIN_INPUT_OPENCV=OFF
make
sudo make install
And 
Apt-get install libv4l-dev

And Customize my linux command to 
./mjpg_streamer -o "output_http.so -w ./www" -i "
-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM),width=3820, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw,width=960, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e"
![Screenshot from 2019-07-17 15-52-27](https://user-images.githubusercontent.com/32286384/61371591-b53f9980-a8b2-11e9-8bb0-f4d85ef1f2aa.png)

**Comment by JetsonHacksNano** [comment]
No comment in over 90 days. Closing.
