### ISSUE TITLE
It doesn't work when I've configured it[BUG]

### ISSUE THREAD

**Issue by yin-qiyu** [JetsonHacksNano/CSI-Camera#51]
**Describe the issue**
After configuring the Gstream,I want to make calls to the CSI camera through the darknet framework, it is stuck in the picture shown in the picture, and then the jetson nano will restart.
![image](https://user-images.githubusercontent.com/71932767/154784063-942d55be-169d-47c6-bfe4-b108a8f37a73.png)

**What version of L4T/JetPack**
L4T/JetPack version:4.4

**What version of OpenCV**
OpenCV version:opencv4.1.1

**Python Version**
Python version if applicable:python3.6

**To Reproduce**
./darknet detector demo cfg/coco.data cfg/yolov4-tiny.cfg yolov4-tiny.weights "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1280, height=720, format=NV12, framerate=30/1 ! nvvidconv flip-method=2 ! video/x-raw, width=1280, height=720, format=BGRx ! videoconvert ! video/x-raw, format=BGR ! appsink"

I installed gstream and called the camera according to the official routine, but the name cannot be displayed

![image](https://user-images.githubusercontent.com/71932767/154786653-73409f4d-fabe-4da8-878c-273c40fb4dbb.png)

I can't start the camera with a simple command either
![image](https://user-images.githubusercontent.com/71932767/154786973-b41c88f8-b111-4438-b283-b581cd7dd59c.png)

**Comment by JetsonHacksNano** [comment]
This does not have anything to do with the code in this repository. Please ask this question on the official NVIDIA Jetson forums: https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70

**Comment by yin-qiyu** [comment]
ok tanks so much
