### ISSUE TITLE
error: Please run 'gdb gst-launch-1.0 9933' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core

### ISSUE THREAD

**Issue by YingUK** [JetsonHacksNano/CSI-Camera#7]
Hi, 

thank you for this great work! 

I have faced this error when trying to test pi camera: Please run 'gdb gst-launch-1.0 9933' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core
I am able to see /dev/video0 listed and I'm using pi camera V2.  Could you please suggest how to fix this issue?

Many thanks,

**Comment by JetsonHacksNano** [comment]
Please describe what code you were running when you encountered the error.
