### ISSUE TITLE
Pink color distortion

### ISSUE THREAD

**Issue by amanattrish** [JetsonHacksNano/CSI-Camera#9]
I am using raspberry pi NoIR camera v2 with jeston nano. Everything is fine except my video stream is capturing pink color videos. Any idea what's happening and how to solve it.

**Comment by fuzzyBatman** [comment]
I second this

![20190907_100421](https://user-images.githubusercontent.com/5787026/64472016-8af2b580-d158-11e9-9eec-3e5a9c913647.png)

**Comment by felixplum** [comment]
NoIR means no IR-filter is being used, i.e. infrared light is being captured.

**Comment by JetsonHacksNano** [comment]
Not quite sure what you are expecting here. If you are using a NoIR camera, then the colors will be a bit off. That's one of the reasons they put an IR filter on the camera.
